### ISSUE TITLE
Pipeline initialization fails with MongoHistory and language.OpenNLP

### ISSUE THREAD

**Issue by jbaker-dstl** [dstl/baleen#30]
Trying to create the following pipeline causes the pipeline initialization to fail on language.OpenNLP.

```
history:
   class: uk.gov.dstl.baleen.history.mongo.MongoHistory

collectionreader:
  class: FolderReader
  folders:
  - corpus

annotators:
- language.OpenNLP
- class: gazetteer.Mongo
  collection: person_gazetteer
  valueField: name
  type: Person
- class: stats.OpenNLP
  model: en-ner-person.bin
  type: Person

consumers:
- Mongo
```
